version: 2
jobs:
  test-sample-project:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.5.1-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "sample-project/Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
          working_directory: sample-project
      - save_cache:
          paths:
            - sample-project/vendor/bundle
          key: v1-dependencies-{{ checksum "sample-project/Gemfile.lock" }}

      # Database setup
      - run:
          command: bundle exec rake db:create db:schema:load
          working_directory: sample-project
      # run tests!
      - run:
          name: run tests
          command: bundle exec rails test -v
          working_directory: sample-project

  danger:
    docker:
       - image: circleci/ruby:2.5.1-node-browsers
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-danger-dependencies-{{ checksum "danger/Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-danger-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
          working_directory: danger
      - save_cache:
          paths:
            - danger/vendor/bundle
          key: v1-danger-dependencies-{{ checksum "danger/Gemfile.lock" }}

      - run:
          # git rootで動かす必要がある
          command: bundle exec danger --verbose --dangerfile=danger/Dangerfile
          environment:
            BUNDLE_GEMFILE: danger/Gemfile

workflows:
  version: 2
  build_all:
    jobs:
      - test-sample-project
      - danger
